apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-v1
  template:
    metadata:
      labels:
        app: webapp-v1
    spec:
      containers:
      - name: webapp
        image: webapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-v1-svc
spec:
  type: NodePort
  selector:
    app: webapp-v1
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-v2
  template:
    metadata:
      labels:
        app: webapp-v2
    spec:
      containers:
      - name: webapp
        image: webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-v2-svc
spec:
  type: NodePort
  selector:
    app: webapp-v2
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002      
